"""Core package for the coding agent."""

from coding_agent.agent import (
    COMPLETED_STOP_REASON,
    DEFAULT_MAX_STEPS,
    FATAL_ERROR_STOP_REASON,
    INTERRUPTED_STOP_REASON,
    MAX_STEPS_STOP_REASON,
    PROVIDER_ERROR_STOP_REASON,
    TRANSIENT_PROVIDER_ERROR_STOP_REASON,
    AgentLoop,
    AgentRunResult,
)
from coding_agent.config import ProviderConfig
from coding_agent.models import (
    AgentState,
    Message,
    ModelResponse,
    ToolCall,
    ToolResult,
    Usage,
)
from coding_agent.provider import FakeProvider, ModelProvider, OpenAICompatibleProvider
from coding_agent.tools import (
    DEFAULT_MAX_LIST_ENTRIES,
    DEFAULT_MAX_OUTPUT_CHARS,
    DEFAULT_MAX_SCAN_ENTRIES,
    LIST_TRUNCATION_MARKER,
    TRUNCATION_MARKER,
    ListFilesArguments,
    ReadFileArguments,
    ToolDispatcher,
    ToolRegistrationError,
    ToolRegistry,
    ToolSpec,
    UnknownToolError,
    Workspace,
    WorkspaceFileError,
    WorkspacePathError,
    WorkspaceTraversalError,
    create_read_only_registry,
    read_only_tool_specs,
)

__version__ = "0.1.0"

__all__ = [
    "AgentState",
    "AgentLoop",
    "AgentRunResult",
    "COMPLETED_STOP_REASON",
    "DEFAULT_MAX_LIST_ENTRIES",
    "DEFAULT_MAX_OUTPUT_CHARS",
    "DEFAULT_MAX_SCAN_ENTRIES",
    "DEFAULT_MAX_STEPS",
    "FATAL_ERROR_STOP_REASON",
    "FakeProvider",
    "INTERRUPTED_STOP_REASON",
    "ListFilesArguments",
    "LIST_TRUNCATION_MARKER",
    "MAX_STEPS_STOP_REASON",
    "Message",
    "ModelProvider",
    "ModelResponse",
    "OpenAICompatibleProvider",
    "ProviderConfig",
    "PROVIDER_ERROR_STOP_REASON",
    "ReadFileArguments",
    "ToolCall",
    "ToolDispatcher",
    "ToolRegistrationError",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "TRUNCATION_MARKER",
    "TRANSIENT_PROVIDER_ERROR_STOP_REASON",
    "Usage",
    "UnknownToolError",
    "Workspace",
    "WorkspaceFileError",
    "WorkspacePathError",
    "WorkspaceTraversalError",
    "create_read_only_registry",
    "read_only_tool_specs",
]
