"""Core package for the coding agent."""

from coding_agent.agent import (
    COMPLETED_STOP_REASON,
    DEFAULT_MAX_STEPS,
    DEFAULT_SYSTEM_PROMPT,
    FATAL_ERROR_STOP_REASON,
    INTERRUPTED_STOP_REASON,
    MAX_STEPS_STOP_REASON,
    PROVIDER_ERROR_STOP_REASON,
    TRANSIENT_PROVIDER_ERROR_STOP_REASON,
    AgentEvent,
    AgentEventCallback,
    AgentLoop,
    AgentRunResult,
)
from coding_agent.approval import ApprovalCallback, ApprovalRequest, request_approval
from coding_agent.command_tools import (
    DEFAULT_COMMAND_OUTPUT_LIMIT_BYTES,
    DEFAULT_COMMAND_TIMEOUT_SECONDS,
    CommandLimits,
    LocalCommandRunner,
    RunCommandArguments,
    run_command_tool_spec,
)
from coding_agent.config import ProviderConfig
from coding_agent.file_tools import (
    DEFAULT_MAX_FILE_BYTES,
    EditFileArguments,
    WriteFileArguments,
    create_workspace_registry,
    edit_file_tool_spec,
    write_file_tool_spec,
)
from coding_agent.models import (
    AgentState,
    Message,
    ModelResponse,
    SessionState,
    ToolCall,
    ToolResult,
    Usage,
)
from coding_agent.provider import FakeProvider, ModelProvider, OpenAICompatibleProvider
from coding_agent.session import AgentSession
from coding_agent.tools import (
    DEFAULT_MAX_LIST_ENTRIES,
    DEFAULT_MAX_OUTPUT_CHARS,
    DEFAULT_MAX_SCAN_ENTRIES,
    LIST_TRUNCATION_MARKER,
    TRUNCATION_MARKER,
    ListFilesArguments,
    ReadFileArguments,
    ToolDispatcher,
    ToolOutput,
    ToolRegistrationError,
    ToolRegistry,
    ToolSpec,
    UnknownToolError,
    Workspace,
    WorkspaceFileError,
    WorkspacePathError,
    WorkspaceTraversalError,
    create_read_only_registry,
    read_only_tool_specs,
)

__version__ = "0.1.0"

__all__ = [
    "ApprovalCallback",
    "ApprovalRequest",
    "AgentState",
    "AgentLoop",
    "AgentRunResult",
    "AgentSession",
    "AgentEvent",
    "AgentEventCallback",
    "COMPLETED_STOP_REASON",
    "DEFAULT_MAX_LIST_ENTRIES",
    "DEFAULT_MAX_FILE_BYTES",
    "DEFAULT_MAX_OUTPUT_CHARS",
    "DEFAULT_MAX_SCAN_ENTRIES",
    "DEFAULT_MAX_STEPS",
    "DEFAULT_SYSTEM_PROMPT",
    "DEFAULT_COMMAND_OUTPUT_LIMIT_BYTES",
    "DEFAULT_COMMAND_TIMEOUT_SECONDS",
    "EditFileArguments",
    "FATAL_ERROR_STOP_REASON",
    "FakeProvider",
    "INTERRUPTED_STOP_REASON",
    "ListFilesArguments",
    "LocalCommandRunner",
    "LIST_TRUNCATION_MARKER",
    "MAX_STEPS_STOP_REASON",
    "Message",
    "ModelProvider",
    "ModelResponse",
    "SessionState",
    "OpenAICompatibleProvider",
    "ProviderConfig",
    "PROVIDER_ERROR_STOP_REASON",
    "ReadFileArguments",
    "RunCommandArguments",
    "ToolCall",
    "ToolDispatcher",
    "ToolOutput",
    "ToolRegistrationError",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "TRUNCATION_MARKER",
    "TRANSIENT_PROVIDER_ERROR_STOP_REASON",
    "Usage",
    "UnknownToolError",
    "Workspace",
    "WorkspaceFileError",
    "WorkspacePathError",
    "WorkspaceTraversalError",
    "WriteFileArguments",
    "CommandLimits",
    "create_read_only_registry",
    "create_workspace_registry",
    "edit_file_tool_spec",
    "read_only_tool_specs",
    "request_approval",
    "run_command_tool_spec",
    "write_file_tool_spec",
]
